qrmv – LightConvex
qrmv Module Procedure
48 statements
Source File
module procedure qrmv private module subroutine qrmv(A, x, y, trans)
y = R @ x
Pointer trick. Workspace query. Actual matrix-vector product. Pointer trick. Workspace query. Actual matrix-vector product.
Arguments
Type Intent Optional Attributes Name
type(qr_type), intent(inout) :: A
real(kind=dp), intent(in) :: x(:)
real(kind=dp), intent(out), target, contiguous :: y(:)
character(len=*), intent(in), optional :: trans
Calls
Source Code
      module subroutine qrmv(A, x, y, trans)
         implicit none(external)
         type(qr_type), intent(inout) :: A
         real(dp), intent(in) :: x(:)
         character(len=*), intent(in), optional :: trans
         real(dp), intent(out), target, contiguous :: y(:)
      end subroutine qrmv
Call graph
qrmv calls assert, gemqr, optval, trmv, x_tmp, xmat