name = "LightConvex"
version = "0.1.0"
license = "license"
author = "Jean-Christophe"
maintainer = "loiseau.jc@gmail.com"
copyright = "Copyright 2025, Jean-Christophe"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
stdlib = "*"
assert = {git="https://github.com/BerkeleyLab/assert.git", preprocess.cpp.macros = ["ASSERTIONS"]}
